import HotelAlphabetical 

hotel = HotelAlphabetical.HotelAlphabetical()
hotel.add("Alice")
hotel.add("Bob")
hotel.add("Charlie")
print(f"\n{hotel}")

hotel.add("Diana")
print(f"\n{hotel}")

hotel.add("Eve")
hotel.add("Frank")
hotel.add("Grace")
hotel.add("Heidi")
hotel.add("Ivan")
hotel.add("Judy")
hotel.add("Karl")
hotel.add("Liam")
hotel.add("Mallory")
hotel.add("Niaj")
hotel.add("Olivia")
hotel.add("Peggy")
hotel.add("Quentin")
hotel.add("Rupert")
hotel.add("Sybil")
hotel.add("Trent")
hotel.add("Uma")
hotel.add("Victor")
hotel.add("Wendy")
hotel.add("Xander")
hotel.add("Yvonne")
hotel.add("Zara")
print(f"\n{hotel}")

hotel.add("Aaron")
hotel.add("Abby")
hotel.add("Abel")
hotel.add("Chuck")
hotel.add("Cathy")
hotel.add("Tom")
print(f"\n{hotel}")